In [3]:
# EXEMPLO 2

import pandas as pd
import numpy as np

# obter dados do isp
try:
    # endereço dados do ISP
    ENDERECO_DADOS = "https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv"

    # ler dados do ISP
    df_isp = pd.read_csv(ENDERECO_DADOS, sep=';', encoding='iso-8859-1')

    # Ver as primeiras linhas (DISPLAY SO EM IPYNB)
    display(df_isp.columns())

except Exception as e:
    print(f"Erro ao obter dados do ISP: {e}")

Erro ao obter dados do ISP: 'Index' object is not callable

In [4]:
# delimitando as variaveis
try:
    df_roubo_veiculos = df_isp[["cisp","mes","ano","munic","regiao","roubo_veiculo"]]
    # totalizando os roubos de veiculos por municipio, regiao e mes
    

except ImportError as e:
    print(f"Erro ao delimitar variáveis: {e}")

In [5]:
# Calculando os Quartis
try:
    array_roubo_veiculos = np.array(df_roubo_veiculos["roubo_veiculo"])

    total = np.sum(array_roubo_veiculos)
    media = np.mean(array_roubo_veiculos)
    mediana = np.median(array_roubo_veiculos)

    # imprimindo os resultados
    print(f"Total de roubos de veículos: {total}")
    print(f"Média de roubos de veículos: {media}")
    print(f"Mediana de roubos de veículos: {mediana}")

    # quartis
    q1 = np.quantile(array_roubo_veiculos, 0.25, method='weibull')
    q3 = np.quantile(array_roubo_veiculos, 0.75, method='weibull')

    print(f"Q1: {q1}")
    print(f"Q3: {q3}")

except Exception as e:
    print(f"Erro ao calcular quartis: {e}")

Total de roubos de veículos: 683038
Média de roubos de veículos: 19.29703921347045
Mediana de roubos de veículos: 4.0
Q1: 0.0
Q3: 24.0

In [6]:
# Criando uma coluna nova, adicionando identificadores
# Concatena a nova coluna no dataframe
try:
    # criando a nova coluna
    # MENOS se for menor que q1, MAIS se for maior que q3 e MAIS OU MENOS se for entre q1 e q3
    df_roubo_veiculos["flag"] = np.where(df_roubo_veiculos["roubo_veiculo"]<=q1,"menos",np.where(df_roubo_veiculos["roubo_veiculo"]>=q3,"mais","mais ou menos"))

    display(df_roubo_veiculos)

    # salvando o dataframe
    df_roubo_veiculos.to_csv("roubo_veiculos_exercicio.csv", sep=';', index=False, encoding='iso-8859-1')

except Exception as e:
    print(f"Erro ao criar coluna nova: {e}")

C:\Users\51134552024.01\AppData\Local\Temp\ipykernel_21692\1922185561.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_roubo_veiculos["flag"] = np.where(df_roubo_veiculos["roubo_veiculo"]<=q1,"menos",np.where(df_roubo_veiculos["roubo_veiculo"]>=q3,"mais","mais ou menos"))

,cisp,mes,ano,munic,regiao,roubo_veiculo,flag
0,1,1,2003,Rio de Janeiro,Capital,5,mais ou menos
1,4,1,2003,Rio de Janeiro,Capital,9,mais ou menos
2,5,1,2003,Rio de Janeiro,Capital,11,mais ou menos
3,6,1,2003,Rio de Janeiro,Capital,27,mais
4,7,1,2003,Rio de Janeiro,Capital,23,mais ou menos
...,...,...,...,...,...,...,...
35391,159,11,2024,Cachoeiras de Macacu,Interior,0,menos
35392,165,11,2024,Mangaratiba,Interior,0,menos
35393,166,11,2024,Angra dos Reis,Interior,0,menos
35394,167,11,2024,Paraty,Interior,0,menos
35395,168,11,2024,Rio Claro,Interior,0,menos